# Generated by Django 4.2.30 on 2026-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobadvert_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='contract_time',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='contract_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='job_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='position_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='recruiter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
