# Generated by Django 4.2.30 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_id_alter_module_content_alter_module_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="module",
            name="university_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
