# Generated by Django 4.2.30 on 2026-06-02

from django.db import migrations, models


def copy_module_school_to_course(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.prefetch_related("modules"):
        module = next(
            (
                item for item in course.modules.all()
                if item.university_name or item.country
            ),
            None,
        )
        if not module:
            continue
        course.university_name = module.university_name
        course.country = module.country
        course.save(update_fields=["university_name", "country"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_module_country_module_university_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="course",
            name="university_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copy_module_school_to_course, migrations.RunPython.noop),
    ]
