# Generated by Django 4.2.30 on 2026-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_taskrecord_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('STOPPED', 'Paused')], default='PENDING', max_length=20),
        ),
    ]
