# Generated by Django 4.2.30 on 2026-06-02

from django.db import migrations, models


def copy_created_at_to_updated_at(apps, schema_editor):
    TaskRecord = apps.get_model("analysis", "TaskRecord")
    for task in TaskRecord.objects.all().only("id", "created_at"):
        task.updated_at = task.created_at
        task.save(update_fields=["updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_alter_taskrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecord",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_created_at_to_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="taskrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
