# Generated by Django 4.2.30 on 2026-06-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('seed_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('pages_seen', models.PositiveIntegerField(default=0)),
                ('courses_created', models.PositiveIntegerField(default=0)),
                ('modules_created', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedCourseCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('matched_alias', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=80)),
                ('confidence', models.FloatField(default=0)),
                ('verified_by_gemini', models.BooleanField(default=False)),
                ('imported_course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_modules', models.JSONField(blank=True, default=list)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='course_scraper.scraperun')),
            ],
            options={
                'ordering': ['-confidence', 'school_name'],
            },
        ),
    ]
